#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sed -i '/listen 80 default_server/i add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
